apiVersion: v1 
kind: Service
metadata:
  name: vprocache01 # this is name service it from -> /src/main/resources/application.properties
spec:
  selector:
    app: vpro-mc
  ports:
  - protocol: TCP
    port: 11211
    targetPort: 11211