apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-psql-claim
  namespace: ibrahimreda
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs

